// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2022 Steadybit GmbH

package extworkload

const (
	WorkloadTargetId = "com.steadybit.extension_newrelic.workload"
	workloadIcon     = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik01IDcuMzIwMDNMMTIuNTAzOCAzTDIxIDcuODkyNVYxNy42Nzg3TDEzLjQ5NzUgMjJWMTguMjM1MkwxNy43MzE0IDE1Ljc5NjNWOS43NzQ5TDEyLjUwMzggNi43NjQ3OUw4LjI2ODYzIDkuMjAyNDJMNSA3LjMyMDAzWk04LjkyMTU2IDIwLjIwNThWMTQuODcyMUw0IDEyVjguMzMyNTVMMTIgMTNWMjJMOC45MjE1NiAyMC4yMDU4WiIgZmlsbD0iIzFEMjYzMiIvPgo8L3N2Zz4K"
)
