{{- if not .Values.newrelic.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newrelic.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  api-key: {{ .Values.newrelic.apiKey | b64enc | quote }}
  insights-collector-api-key: {{ .Values.newrelic.insightsCollectorApiKey | b64enc | quote }}
{{- end }}
